version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:$GITLAB_VERSION'
    restart: always
    hostname: '$GITLAB_HOST'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '$GITLAB_EXTERNAL_URL'
        letsencrypt['enable'] = $GITLAB_LETSENCRYPT
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = '$SMTP_HOST'
        gitlab_rails['smtp_port'] = $SMTP_PORT
        gitlab_rails['smtp_user_name'] = '$EMAIL_USER'
        gitlab_rails['smtp_password'] = '$EMAIL_PASS'
        gitlab_rails['smtp_domain'] = '$SMTP_DOMAIN'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = '$GITLAB_EMAIL'
        gitlab_rails['gitlab_email_reply_to'] = '$GITLAB_EMAIL_REPLY_TO'
        gitlab_rails['incoming_email_enabled'] = true
        gitlab_rails['incoming_email_address'] = '$GITLAB_INCOMING_EMAIL_ADDRESS'
        gitlab_rails['incoming_email_email'] = '$EMAIL_USER'
        gitlab_rails['incoming_email_password'] = '$EMAIL_PASS'
        gitlab_rails['incoming_email_host'] = '$SMTP_HOST'
        gitlab_rails['incoming_email_port'] = $IMAP_PORT
        gitlab_rails['incoming_email_ssl'] = true
        gitlab_rails['incoming_email_mailbox_name'] = 'inbox'
        gitlab_rails['incoming_email_idle_timeout'] = 60
        gitlab_rails['incoming_email_delete_after_delivery'] = true
        gitlab_rails['incoming_email_expunge_deleted'] = true

        puma['worker_processes'] = 0
        sidekiq['max_concurrency'] = 10
        prometheus_monitoring['enable'] = false
    ports:
      - '$PORT_HTTP:80'
      - '$PORT_HTTPS:443'
      - '$PORT_SSH::22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
